// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDDLYqUJJqyioJ08caHsBLlFreD_W1KPYo',
    appId: '1:92522712625:web:238acdfe0d7c14eba84f10',
    messagingSenderId: '92522712625',
    projectId: 'fall-d37f7',
    authDomain: 'fall-d37f7.firebaseapp.com',
    storageBucket: 'fall-d37f7.firebasestorage.app',
    measurementId: 'G-8RJL2SJZ6V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5h0ehUTjQuiaC9E-IsV91Xw7vUZnRNdA',
    appId: '1:92522712625:android:02987b380d5c6621a84f10',
    messagingSenderId: '92522712625',
    projectId: 'fall-d37f7',
    storageBucket: 'fall-d37f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA70Gqxqp5wcgfQ6UUSfVIQWEoXAi8u09Y',
    appId: '1:92522712625:ios:05ebbaa51ffecc15a84f10',
    messagingSenderId: '92522712625',
    projectId: 'fall-d37f7',
    storageBucket: 'fall-d37f7.firebasestorage.app',
    iosBundleId: 'com.example.seniorFallDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA70Gqxqp5wcgfQ6UUSfVIQWEoXAi8u09Y',
    appId: '1:92522712625:ios:05ebbaa51ffecc15a84f10',
    messagingSenderId: '92522712625',
    projectId: 'fall-d37f7',
    storageBucket: 'fall-d37f7.firebasestorage.app',
    iosBundleId: 'com.example.seniorFallDetection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDDLYqUJJqyioJ08caHsBLlFreD_W1KPYo',
    appId: '1:92522712625:web:05c50a0f32b2b08ea84f10',
    messagingSenderId: '92522712625',
    projectId: 'fall-d37f7',
    authDomain: 'fall-d37f7.firebaseapp.com',
    storageBucket: 'fall-d37f7.firebasestorage.app',
    measurementId: 'G-JRF1WZQY3X',
  );

}